In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
# Grap the element 5
arr_2d[0,0]

5

In [29]:
# Grap the element 35
arr_2d[2,0]

35

In [30]:
# Grap the elements 10,15,25,30
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
# Grap the elements 5,10,15,20,25,30
arr_2d[0:2,]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [37]:
# Grap the elements 20,25,30,35,40,45
arr_2d[1:,]

array([[20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_to_grap = np.arange(0, 100, 5)

In [63]:
arr_to_grap

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [61]:
arr_to_grap.shape

(4, 5)

In [62]:
arr_to_grap = arr_to_grap.reshape(4,5)

In [60]:
# Grap the elements 50,55,60,65,70
arr_to_grap[2:]

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [65]:
# Grap the elements 10,15,20
arr_to_grap[0,2:]

array([10, 15, 20])

In [66]:
arr = np.arange(1,11)

In [67]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
boolean_arr = arr > 5

In [69]:
boolean_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [70]:
final_array = arr[boolean_arr]

In [71]:
final_array

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [75]:
arr[arr<3]

array([1, 2])

In [76]:
arr_2d = np.arange(50).reshape(5,10)

In [77]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
# Grap 14,15
arr_2d[1,4:6]

array([14, 15])