In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [18]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [20]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [29]:
np.linspace(0,5,5)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [30]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [33]:
np.random.rand(5)

array([ 0.80434818,  0.96670631,  0.04135042,  0.69317771,  0.13449541])

In [36]:
np.random.randint(1, 50, size=5)

array([17, 18, 29, 30, 14])

In [38]:
np.random.randn(3,3)

array([[ 0.62092976,  1.18551707, -0.70538672],
       [ 0.17162927, -0.21220871, -0.47859399],
       [-0.46226439, -0.60102998,  0.54644474]])

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr = np.random.randint(0,50,10)

In [42]:
ranarr

array([32, 46,  0, 30, 44, 18, 35, 18, 39, 43])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.max()

46

In [45]:
ranarr.argmax()

1

In [46]:
ranarr.min()

0

In [47]:
ranarr.argmin()

2

In [48]:
arr.shape

(25,)

In [49]:
arr = arr.reshape(5,5)

In [50]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.dtype

dtype('int64')